global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - rules/*.yml

scrape_configs:
  - job_name: node-exporter
    static_configs:
      - targets:
          - "exporter:9100"

  - job_name: ping-exporter
    static_configs:
      - targets:
          - "ping-exporter:9427"
