global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - rules/*.yml

scrape_configs:
  - job_name: node-exporter
    static_configs:
      - targets:
          - "exporter:9100"

  - job_name: ping-exporter
    static_configs:
      - targets:
          - "ping-exporter:9427"

  - job_name: mariadb_exporter
    static_configs:
      - targets:
          - "db-exporter:9104"